### ISSUE TITLE
tomatotomato-http

### ISSUE THREAD

**Issue by kesla** [well-knits/tomatotomato#2]
I'm working on a `tomatotomato-http`-client - a simple http-server showing the state of the current pomodoro.

**Comment by bnvk** [comment]
Oooooo. I think this project is pretty neat. I'd love to help do the UI for this feature :smile:

**Comment by ellell** [comment]
@bnvk go go go! :)

**Comment by kesla** [comment]
@bnvk I did create a super simple UI for this but I'd love some improvements. Let me know of there's anything you want help on.

**Comment by bnvk** [comment]
@kesla yah I saw that in the browser. It works. Yay :grin: few questions as I haven't really dug into the codebase at all that if you could answer would give me a jump start!

- Is there a value like "Total Number of Users" connected to a given session accessible in http? 
- Is there any sort of "log" that the server keeps of sessions recorded since starting?

**Comment by kesla** [comment]
#3
